### ISSUE TITLE
Time not settable

### ISSUE THREAD

**Issue by iStehle** [yeah/hassio-addons#2]
Hey,

the docker homegear container is running on utc and i can't find an option to change that. This means that all my times on the devices are off by one hour. 

maybe this helps future: https://community.home-assistant.io/t/timezone-resinos-docker/17522/21

**Comment by pschneider86** [comment]
I'm struggling with the same issue here.

**Comment by iStehle** [comment]
seems that we only need to install tzdata into the docker img, trying that out right now

**Comment by pschneider86** [comment]
I'm running the recent version of both Hass.IO and this addon - but still getting the wrong timezone. Is there a config param I need to set?
